# Generated by Django 5.2.17 on 2026-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_stident_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
