# Generated by Django 5.2.17 on 2026-08-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_teachingassignment'),
        ('exam', '0002_result_grade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='teaching_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academic.teachingassignment'),
        ),
    ]
