# Generated by Django 5.2.17 on 2026-08-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_teachingassignment'),
        ('attendance', '0002_attendance_teaching_assignment'),
        ('students', '0002_rename_stident_student'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_attendance_per_day',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teaching_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.teachingassignment'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'teaching_assignment', 'date'), name='unique_student_attendance_per_assignment_day'),
        ),
    ]
