# Generated by Django 5.2.17 on 2026-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_teachingassignment'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('teaching_assignment', 'day', 'start_time', 'end_time'), name='unique_routine_schedule'),
        ),
    ]
